### PR TITLE
change date separator in filenames to '-', update bounds metadata

### PR DESCRIPTION
**Pull request by klindsay28**
bounds metadata mods fix https://github.com/ESCOMP/MOM_interface/issues/107

New time and time:bounds metadata is
```
    double time(time) ;
      time:units = "days since 0001-01-01 00:00:00" ;
      time:long_name = "time" ;
      time:axis = "T" ;
      time:calendar = "noleap" ;
      time:bounds = "time_bounds" ;

    double time_bounds(time,nbnd) ;
      time_bounds:units = "days since 0001-01-01 00:00:00" ;
      time_bounds:long_name = "time interval endpoints" ;
      time_bounds:calendar = "noleap" ;
```

The date separator change goes with PR to https://github.com/ESCOMP/MOM_interface,
so that files with changed names get archived by short-term archiver and testing baseline generation works.
Once that PR is submitted, I will update this PR with a link to it.

### CODE REVIEW

**Comment by jedwards4b** [comment]
Thank you Keith - should this PR be marked as draft until the MOM_interface PR is submitted or can it be merged first?

**Comment by klindsay28** [comment]
Corresponding MOM_interface PR is https://github.com/ESCOMP/MOM_interface/pull/144

**Comment by klindsay28** [comment]
The merging of this PR should be coordinated with the merging of the MOM_interface PR.
If one runs with this PR and not the MOM_interface PR, MOM6 output will not get archived by the short-term archiver.

**Comment by klindsay28** [comment]
I don't appear to have permission to suggest reviewers, so I'm writing here to state that this PR is ready for review.

**Review by alperaltuntas — APPROVED** [review]

**Review by alperaltuntas — APPROVED** [review]

**Pull request merged**
